apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-example-webserver
  labels:
    name: go-example-webserver
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: go-example-webserver
    spec:
      containers:
        - name: go-example-webserver
          image: gcr.io/container-solutions-workshops/<YOUR_APP_NAME>
          ports:
            - containerPort: 8081
