apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-example-webserver
  labels:
    name: go-example-webserver-prod
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: go-example-webserver
        env: prod
    spec:
      containers:
        - name: go-example-webserver
          image: gcr.io/adidas-173709/<YOUR_APP_NAME>
          ports:
            - containerPort: 8080
